version: '3.1'
services:

  web:
    build:
      context: ./
      dockerfile: .docker/web.dockerfile
    volumes:
      - ./:/var/www
    ports:
      - "80:80"
    links:
      - app

  app:
    build:
      context: ./
      dockerfile: .docker/app.dockerfile
    volumes:
      - ./:/var/www

  #MySQL Service
  db:
    image: mariadb
    restart: always
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 48344951
      MYSQL_DATABASE: spj_uptd